package com.LDLS.Litigation.Project.BillingModule.Entities;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

@Entity(name = "time_tracking") // Use a more descriptive name for the entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class TimeTracking {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "staff_id")
    private Staff staff; // Reference to the associated Staff member

    @ManyToOne
    @JoinColumn(name = "case_id") // Assuming a foreign key column for Case
    private Case theCase; // Foreign key referencing Case entity

    private Date date;
    private BigDecimal hoursSpent;
    private String description; // Brief description of work performed

    // Getters and setters (generated by Lombok's @Data annotation)
}